using Microsoft.EntityFrameworkCore;
using WordOs.Domain.Common;
using WordOs.Domain.Levels;
using WordOs.Domain.Lexicon;
using WordOs.Domain.Placement;
using WordOs.Domain.Review;
using WordOs.Domain.Sessions;
using WordOs.Domain.Users;
using WordOs.Domain.Words;

namespace WordOs.Infrastructure.Persistence;

/// <summary>
/// The WordOS database.
/// </summary>
/// <remarks>
/// The schema is defined here and created by EF Core migrations — never by
/// hand, and never from the client. Constraints enforce the rules rather than
/// trusting application code (docs/07-SECURITY.md §10): the duplicate rule is a
/// unique index, and the daily target range is a check constraint.
///
/// Everything goes through parameterised queries; there is no raw SQL built
/// from user input anywhere in this project.
/// </remarks>
public class WordOsDbContext(DbContextOptions<WordOsDbContext> options)
    : DbContext(options)
{
    public DbSet<User> Users => Set<User>();

    public DbSet<UserInterest> UserInterests => Set<UserInterest>();

    public DbSet<RefreshToken> RefreshTokens => Set<RefreshToken>();

    public DbSet<SkillLevel> SkillLevels => Set<SkillLevel>();

    public DbSet<LevelChangeRecord> LevelChanges => Set<LevelChangeRecord>();

    /// <summary>The append-only activity log (Part 3 §34–§35).</summary>
    public DbSet<ActivityEvent> ActivityEvents => Set<ActivityEvent>();

    public DbSet<Word> Words => Set<Word>();

    public DbSet<WordSkillState> WordSkillStates => Set<WordSkillState>();

    public DbSet<WordEvent> WordEvents => Set<WordEvent>();

    public DbSet<LexiconEntry> LexiconEntries => Set<LexiconEntry>();

    public DbSet<PlacementSession> PlacementSessions => Set<PlacementSession>();

    public DbSet<PlacementAnswer> PlacementAnswers => Set<PlacementAnswer>();

    public DbSet<SkillSession> SkillSessions => Set<SkillSession>();

    public DbSet<SessionItem> SessionItems => Set<SessionItem>();

    public DbSet<WordExposure> WordExposures => Set<WordExposure>();

    public DbSet<WeeklyReview> WeeklyReviews => Set<WeeklyReview>();

    public DbSet<WeeklyReviewItem> WeeklyReviewItems => Set<WeeklyReviewItem>();

    protected override void OnModelCreating(ModelBuilder b)
    {
        // Keys are generated by the domain (Guid.CreateVersion7 in each
        // entity), never by the store.
        //
        // This must be declared. EF otherwise infers ValueGeneratedOnAdd for a
        // Guid key and then decides Added-vs-Modified by whether the key is
        // still the default value — so an entity that assigned its own id in a
        // property initialiser looks like a row that already exists. EF emits
        // UPDATE, matches nothing, and throws a concurrency exception. It cost
        // two debugging rounds before the pattern was clear.
        foreach (var entity in b.Model.GetEntityTypes())
        {
            var key = entity.FindPrimaryKey()?.Properties
                .SingleOrDefault(p => p.ClrType == typeof(Guid));
            key?.ValueGenerated = Microsoft.EntityFrameworkCore.Metadata.ValueGenerated.Never;
        }

        // Enums are stored as text, not ordinals: a readable database, and
        // inserting a value in the middle of an enum can never silently
        // re-map existing rows.
        b.Entity<User>(e =>
        {
            e.ToTable("users");
            e.HasKey(x => x.Id);
            e.Property(x => x.Email).HasMaxLength(320).IsRequired();
            e.HasIndex(x => x.Email).IsUnique();
            e.Property(x => x.PasswordHash).HasMaxLength(256).IsRequired();
            e.Property(x => x.DisplayName).HasMaxLength(120).IsRequired();
            e.Property(x => x.PhoneCountryCode).HasMaxLength(6);
            e.Property(x => x.PhoneNumber).HasMaxLength(20);
            e.Property(x => x.Role).HasConversion<string>().HasMaxLength(16);
            e.Property(x => x.OnboardingStage)
                .HasConversion<string>().HasMaxLength(16);
            e.Property(x => x.TimeZone).HasMaxLength(64);

            e.HasMany(x => x.Interests)
                .WithOne().HasForeignKey(x => x.UserId)
                .OnDelete(DeleteBehavior.Cascade);
            e.HasMany(x => x.SkillLevels)
                .WithOne().HasForeignKey(x => x.UserId)
                .OnDelete(DeleteBehavior.Cascade);
            e.HasMany(x => x.LevelChanges)
                .WithOne().HasForeignKey(x => x.UserId)
                .OnDelete(DeleteBehavior.Cascade);

            e.Navigation(x => x.Interests).UsePropertyAccessMode(PropertyAccessMode.Field);
            e.Navigation(x => x.SkillLevels).UsePropertyAccessMode(PropertyAccessMode.Field);
            e.Navigation(x => x.LevelChanges).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        b.Entity<UserInterest>(e =>
        {
            e.ToTable("user_interests");
            e.HasKey(x => x.Id);
            // Length cap at the schema level, not only in a DTO validator.
            e.Property(x => x.Interest).HasMaxLength(40).IsRequired();
            e.HasIndex(x => new { x.UserId, x.Interest }).IsUnique();
        });

        b.Entity<RefreshToken>(e =>
        {
            e.ToTable("refresh_tokens");
            e.HasKey(x => x.Id);
            e.Property(x => x.TokenHash).HasMaxLength(64).IsRequired();
            // Redemption looks the token up by hash, so this must be indexed
            // and unique — two rows with the same hash would be ambiguous.
            e.HasIndex(x => x.TokenHash).IsUnique();
            e.HasIndex(x => new { x.UserId, x.FamilyId });
            e.HasOne<User>().WithMany()
                .HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
        });

        b.Entity<SkillLevel>(e =>
        {
            e.ToTable("user_skill_levels");
            e.HasKey(x => x.Id);
            e.Property(x => x.Skill).HasConversion<string>().HasMaxLength(16);
            // Nullable for SPELLING, which is measured but carries no CEFR
            // band (ADR-008).
            e.Property(x => x.UserSelectedLevel)
                .HasConversion<string?>().HasMaxLength(8);
            e.Property(x => x.SystemAssessedLevel)
                .HasConversion<string?>().HasMaxLength(8);
            e.Property(x => x.SpellingSupportMode)
                .HasConversion<string?>().HasMaxLength(16);
            e.HasIndex(x => new { x.UserId, x.Skill }).IsUnique();
            e.ToTable(t => t.HasCheckConstraint(
                "ck_skill_levels_daily_target",
                "\"DailyTargetWords\" BETWEEN 5 AND 15"));
        });

        b.Entity<LevelChangeRecord>(e =>
        {
            e.ToTable("level_changes");
            e.HasKey(x => x.Id);
            e.Property(x => x.Skill).HasConversion<string>().HasMaxLength(16);
            e.Property(x => x.PreviousLevel)
                .HasConversion<string?>().HasMaxLength(8);
            e.Property(x => x.NewLevel).HasConversion<string?>().HasMaxLength(8);
            e.Property(x => x.ChangeType).HasConversion<string>().HasMaxLength(32);
            e.Property(x => x.Reason).HasMaxLength(256);
            e.HasIndex(x => new { x.UserId, x.CreatedAt });
        });

        b.Entity<ActivityEvent>(e =>
        {
            e.ToTable("activity_events");
            e.HasKey(x => x.Id);
            e.Property(x => x.Type).HasConversion<string>().HasMaxLength(32);
            e.Property(x => x.Skill).HasConversion<string?>().HasMaxLength(16);

            // The two questions the dashboard asks: what did this learner do,
            // and what happened across everyone in a window.
            e.HasIndex(x => new { x.UserId, x.CreatedAt });
            e.HasIndex(x => new { x.Type, x.CreatedAt });

            e.HasOne<User>().WithMany()
                .HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
        });

        b.Entity<Word>(e =>
        {
            e.ToTable("words");
            e.HasKey(x => x.Id);
            e.Property(x => x.SenseId).HasMaxLength(64).IsRequired();
            e.Property(x => x.Text).HasMaxLength(128).IsRequired();
            e.Property(x => x.Meaning).HasMaxLength(256).IsRequired();
            e.Property(x => x.DefinitionEn).HasMaxLength(1024);
            e.Property(x => x.PartOfSpeech).HasMaxLength(32);
            e.Property(x => x.CefrLevel).HasConversion<string>().HasMaxLength(8);
            e.Property(x => x.State).HasConversion<string>().HasMaxLength(16);
            e.Property(x => x.CurrentSkill)
                .HasConversion<string?>().HasMaxLength(16);

            // The duplicate rule lives in the schema, not only in code: one
            // learner may hold a given sense exactly once (ADR-012).
            e.HasIndex(x => new { x.UserId, x.SenseId }).IsUnique();

            // Every session query filters on these three.
            e.HasIndex(x => new { x.UserId, x.State, x.CurrentSkill });

            e.HasOne<User>().WithMany()
                .HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);

            e.HasMany(x => x.Skills)
                .WithOne().HasForeignKey(x => x.WordId)
                .OnDelete(DeleteBehavior.Cascade);
            e.HasMany(x => x.Events)
                .WithOne().HasForeignKey(x => x.WordId)
                .OnDelete(DeleteBehavior.Cascade);

            e.Navigation(x => x.Skills).UsePropertyAccessMode(PropertyAccessMode.Field);
            e.Navigation(x => x.Events).UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        b.Entity<WordSkillState>(e =>
        {
            e.ToTable("word_skill_states");
            e.HasKey(x => x.Id);
            e.Property(x => x.Skill).HasConversion<string>().HasMaxLength(16);
            e.Property(x => x.Status).HasConversion<string>().HasMaxLength(16);
            // Exactly five per word, one per skill.
            e.HasIndex(x => new { x.WordId, x.Skill }).IsUnique();
            // Eligibility scan: "which words are due for this skill now?"
            e.HasIndex(x => new { x.Skill, x.Status, x.AvailableAt });
        });

        b.Entity<WordEvent>(e =>
        {
            e.ToTable("word_events");
            e.HasKey(x => x.Id);
            e.Property(x => x.Type).HasConversion<string>().HasMaxLength(32);
            e.Property(x => x.Skill).HasConversion<string?>().HasMaxLength(16);
            e.HasIndex(x => new { x.WordId, x.CreatedAt });
        });

        b.Entity<PlacementSession>(e =>
        {
            e.ToTable("placement_sessions");
            e.HasKey(x => x.Id);
            e.Property(x => x.CurrentItemId).HasMaxLength(64);
            e.HasIndex(x => new { x.UserId, x.IsComplete });
            e.HasOne<User>().WithMany()
                .HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
            e.HasMany(x => x.Answers)
                .WithOne().HasForeignKey(x => x.SessionId)
                .OnDelete(DeleteBehavior.Cascade);
            e.Navigation(x => x.Answers)
                .UsePropertyAccessMode(PropertyAccessMode.Field);
        });

        b.Entity<PlacementAnswer>(e =>
        {
            e.Property(x => x.Level).HasConversion<string>().HasMaxLength(8);
            e.Property(x => x.Domain).HasConversion<string>().HasMaxLength(16);
            e.Property(x => x.AlsoEvidenceFor)
                .HasConversion<string?>().HasMaxLength(16);
            // The learner's own words. Generous but bounded — a spoken answer
            // transcript is longer than a typed one.
            e.Property(x => x.RawAnswer).HasMaxLength(4000);
            e.Property(x => x.EvaluationJson).HasMaxLength(4000);
            e.ToTable("placement_answers");
            e.HasKey(x => x.Id);
            e.Property(x => x.ItemId).HasMaxLength(64).IsRequired();
            e.Property(x => x.Skill).HasConversion<string>().HasMaxLength(16);
            // One answer per item per run — the engine never re-asks, and a
            // replay must not be able to add a second score.
            e.HasIndex(x => new { x.SessionId, x.ItemId }).IsUnique();
        });

        b.Entity<SkillSession>(e =>
        {
            e.ToTable("skill_sessions");
            e.HasKey(x => x.Id);
            e.Property(x => x.Skill).HasConversion<string>().HasMaxLength(16);
            e.Property(x => x.LevelUsed).HasConversion<string>().HasMaxLength(8);
            e.Property(x => x.PromptVersion).HasMaxLength(64);
            e.Property(x => x.AiModel).HasMaxLength(64);
            // Bounded generously: one entry per content word in a passage.
            e.Property(x => x.GlossaryJson).HasMaxLength(20000);
            e.HasIndex(x => new { x.UserId, x.Skill, x.IsComplete });
            e.HasOne<User>().WithMany()
                .HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
            e.HasMany(x => x.Items)
                .WithOne().HasForeignKey(x => x.SessionId)
                .OnDelete(DeleteBehavior.Cascade);
            e.Navigation(x => x.Items)
                .UsePropertyAccessMode(PropertyAccessMode.Field);

            // Both are computed views over Items. Left alone, EF discovers them
            // as extra navigations and adds a second, shadow foreign key —
            // convention does not require a setter for a navigation property.
            e.Ignore(x => x.Queue);
            e.Ignore(x => x.CurrentItem);
        });

        b.Entity<SessionItem>(e =>
        {
            e.ToTable("session_items");
            e.HasKey(x => x.Id);
            e.Property(x => x.Type).HasConversion<string>().HasMaxLength(24);
            e.Property(x => x.Prompt).HasMaxLength(2048);
            e.Property(x => x.CorrectAnswer).HasMaxLength(512);
            e.Property(x => x.Clue).HasMaxLength(1024);
            e.Property(x => x.ClueKind).HasConversion<string?>().HasMaxLength(24);
            e.Property(x => x.PromptKey).HasConversion<string?>().HasMaxLength(32);
            e.Property(x => x.InputMode).HasConversion<string?>().HasMaxLength(16);
            // The hint ladder: an ordered array, so it is stored as JSON.
            e.Property(x => x.HintsJson).HasColumnType("jsonb");
            e.Property(x => x.AudioText).HasMaxLength(4096);
            e.Property(x => x.LastAnswer).HasMaxLength(4000);
            e.HasIndex(x => new { x.SessionId, x.Position });
        });

        b.Entity<WordExposure>(e =>
        {
            e.ToTable("word_exposures");
            e.HasKey(x => x.Id);
            e.Property(x => x.Source).HasConversion<string>().HasMaxLength(24);
            e.HasOne<Word>().WithMany()
                .HasForeignKey(x => x.WordId).OnDelete(DeleteBehavior.Cascade);

            // The rule, enforced by the database rather than by remembering to
            // check: one exposure per word per generating event. Application
            // code guards it too, but this is what makes a concurrent retry
            // safe (rule R8 — an inflated count can retire a word early).
            e.HasIndex(x => new { x.WordId, x.Source, x.SourceId }).IsUnique();
            e.HasIndex(x => x.SourceId);
        });

        b.Entity<WeeklyReview>(e =>
        {
            e.ToTable("weekly_reviews");
            e.HasKey(x => x.Id);
            e.HasIndex(x => new { x.UserId, x.IsComplete });
            e.HasOne<User>().WithMany()
                .HasForeignKey(x => x.UserId).OnDelete(DeleteBehavior.Cascade);
            e.HasMany(x => x.Items)
                .WithOne().HasForeignKey(x => x.ReviewId)
                .OnDelete(DeleteBehavior.Cascade);
            e.Navigation(x => x.Items)
                .UsePropertyAccessMode(PropertyAccessMode.Field);
            e.Ignore(x => x.Queue);
        });

        b.Entity<WeeklyReviewItem>(e =>
        {
            e.ToTable("weekly_review_items");
            e.HasKey(x => x.Id);
            e.Property(x => x.Prompt).HasMaxLength(128);
            e.Property(x => x.CorrectAnswer).HasMaxLength(512);
            e.HasIndex(x => new { x.ReviewId, x.Position });
            e.HasOne<Word>().WithMany()
                .HasForeignKey(x => x.WordId).OnDelete(DeleteBehavior.Cascade);
        });

        b.Entity<LexiconEntry>(e =>
        {
            e.ToTable("lexicon_entries");
            e.HasKey(x => x.SenseId);
            e.Property(x => x.SenseId).HasMaxLength(64);
            e.Property(x => x.Text).HasMaxLength(128).IsRequired();
            e.Property(x => x.TextNormalized).HasMaxLength(128).IsRequired();
            e.Property(x => x.Lemma).HasMaxLength(128);
            e.Property(x => x.PartOfSpeech).HasMaxLength(32);
            e.Property(x => x.DefinitionEn).HasMaxLength(2048);
            e.Property(x => x.MeaningAr).HasMaxLength(512).IsRequired();
            e.Property(x => x.MeaningArNormalized).HasMaxLength(512).IsRequired();
            e.Property(x => x.CefrLevel).HasConversion<string?>().HasMaxLength(8);
            e.Property(x => x.SourceFlags).HasMaxLength(128);

            // Prefix autocomplete: `bo` → `book`. text_pattern_ops makes
            // LIKE 'bo%' an index scan rather than a sequential scan.
            e.HasIndex(x => x.TextNormalized)
                .HasDatabaseName("ix_lexicon_text_prefix")
                .HasOperators("text_pattern_ops");
            e.HasIndex(x => new { x.TextNormalized, x.PartOfSpeech });
        });
    }
}
